version: '3'

services:

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: "${REPOSITORY_NAME}_client"
    container_name: "${REPOSITORY_NAME}_client"
    volumes:
      - './client/src/:/app'
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

  cp:
    build:
      context: .
      dockerfile: cp/Dockerfile
    image: "${REPOSITORY_NAME}_cp"
    container_name: "${REPOSITORY_NAME}_cp"
    volumes:
      - './cp/src/:/app'
    ports:
      - "${CP_PORT}:${CP_PORT}"

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "${DB_PORT}:3306"
    container_name: "${REPOSITORY_NAME}_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - 'api-mysql:/var/lib/mysql'

  redis:
    image: 'redis:alpine'
    container_name: "${REPOSITORY_NAME}_redis"
    volumes:
      - 'api-redis:/data'

volumes:
  api-mysql:
    driver: local
  api-redis:
    driver: local
