version: '3'

services:

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: "${REPOSITORY_NAME}_client"
    container_name: "${REPOSITORY_NAME}_client"
    volumes:
      - './client/src/:/app'
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

  cp:
    build:
      context: .
      dockerfile: cp/Dockerfile
    image: "${REPOSITORY_NAME}_cp"
    container_name: "${REPOSITORY_NAME}_cp"
    volumes:
      - './cp/src/:/app'
    ports:
      - "${CP_PORT}:${CP_PORT}"
